### ISSUE TITLE
Minecraft profiles listed in profile selection screen

### ISSUE THREAD

**Issue by juozaspo** [Treer/amidstest#27]
Using the switch profile option from the menu, it shows minecraft profiles listed as shown in screenshot below.
![Profile Selector 2019-07-04 08:26:12](https://user-images.githubusercontent.com/6626242/60641787-163c8b80-9e36-11e9-8a92-39fc2e764ace.png)
It should not even try to access conents of .minecraft folder or avoid some files/folders in it if the former is not possible.

P.s.: Old Version shown in the screenshot is a very old version of Minecraft Alpha.

**Comment by Treer** [comment]
Explanation [here](https://github.com/Treer/Amidst-for-Minetest/issues/10#issuecomment-392425497) and [here](https://github.com/Treer/Amidst-for-Minetest/issues/10#issuecomment-392551092).

A rewrite with no attempt to support Minecraft would allow many features, but it's a big job.

**Comment by Treer** [comment]
Minecraft features are hidden in 1.4-3
